School/School/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('management.urls')),
    path('admin/', admin.site.urls),
]

School/management/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view
from .decorators import unauthorized_required
from django.conf import settings
from django.conf.urls.static import static
from .forms import UserPasswordChange, UserPasswordReset, UserSetPasswordForm

urlpatterns = [
    path('', views.home, name="homepage"),
    path('login/', views.custom_login_view, name="login"),
    path('logout/', views.logout_view, name='logout'),
    path('passwordchange/', auth_view.PasswordChangeView.as_view(template_name='change-password.html', form_class=UserPasswordChange, success_url='/passwodchangedone/'), name='passwordchange'),
    path('password-reset/', unauthorized_required(redirect_to='homepage')(auth_view.PasswordResetView.as_view(template_name='password-reset.html', form_class=UserPasswordReset)), name='password_reset'),
    path('password-reset/done/', unauthorized_required(redirect_to='homepage')(auth_view.PasswordResetDoneView.as_view(template_name='password-reset-done.html')), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', unauthorized_required(redirect_to='homepage')(auth_view.PasswordResetConfirmView.as_view(template_name='password-reset-confirm.html', form_class=UserSetPasswordForm)), name='password_reset_confirm'),
    path('password-reset-complete/', unauthorized_required(redirect_to='homepage')(auth_view.PasswordResetCompleteView.as_view(template_name='password-reset-complete.html',)), name='password_reset_complete'),
    path('groups/', views.group, name='groups'),
    path('group-edit/<int:id>', views.group_edit, name='group_edit'),
    path('group-add/', views.group_add_view.as_view(), name='group_add'),
    path('group-delete/', views.group_delete, name='group_delete'),
    path("subjects/", views.SubjectView.as_view(), name="subject"),
    path('subject-delete/', views.subject_delete, name='subject_delete'),
    path('subject-edit/', views.subject_edit, name='subject edit'),
    path('subject-update/', views.subject_update, name='subject update'),
    path('teachers/', views.TeacherList, name='teachers'),
    path('teacher-add/', views.TeacherAdd.as_view(), name='teacher add'),
    path('teacher/view/<int:id>/', views.TeacherDetails, name='teacher_detail'),
    path('teacher/edit/<int:id>', views.TeacherEdit.as_view(), name='teacher edit'),
    path('teacher-delete/', views.TeacherDelete, name='teacher_delete'),
    path('classes/', views.StudentClassView.as_view(), name='classes'),
    path('class-delete/', views.StudentClassDelete, name='class_delete'),
    path('class-edit/', views.StudentClassEdit, name='class_edit'),
    path('class-update/', views.StudentClassUpdate, name='class_update'),
    path('students/', views.StudentList, name='students'),
    path('student-add/', views.StudentAdd.as_view(), name='student add'),
    path('student/edit/<int:id>/', views.StudentEdit.as_view(), name='student edit'),
    path('student/view/<int:id>/', views.StudentDetails, name='student_detail'),
    path('student-delete/', views.StudentDelete, name='student_delete'),
    path('student-search/', views.StudentSearchFilter, name='student search'),
    path('fee-structure/', views.FeeStructureList, name='fee structure list'),
    path('fee-structure-add/', views.FeeStructureAdd.as_view(), name='fee structure add'),
    path('fee-structure/edit/<int:fee_id>', views.FeeStructureEdit.as_view(), name='fee structure edit'),
    path('fee-structure-delete/', views.FeeStructureDelete, name='fee structure delete'),
    path('fee-payment-student-list/', views.FeeStudentList, name='fee payment student list'),
    path('fee-payment/<int:id>/', views.FeeStudentPay.as_view(), name='fee payment'),
    path('transaction-history/', views.TransactionHistoryList, name='transaction history'),
    path('transaction-history/detail/<int:id>/', views.TransactionHistoryDetail, name='transaction history detail'),
    path('fee-register/', views.FeeRegister, name='fee register'),
    path('change-password/', auth_view.PasswordChangeView.as_view(template_name='change-password.html', form_class=UserPasswordChange), name='change_password'),
    path('password-reset-complete/', auth_view.PasswordResetCompleteView.as_view(template_name='password-reset-complete.html'), name='password_change_done'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

School/management/forms.py
import datetime
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm, PasswordChangeForm, SetPasswordForm, password_validation
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import Group, Permission

from .models import DISTRICT_CHOICES, Teacher, Subject, StudentClass, Students, FeeStructure, TransactionHistory, \
    FeePayment

email_pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
phone_pattern = r'^\+?1?\d{9,15}$'
password_pattern = r'^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$'
name_pattern = r'^[a-zA-Z]+(?: [a-zA-Z]+)*$'


class UserPasswordReset(PasswordResetForm):
    email = forms.EmailField(label=_('Email Address'), max_length=255, required=True,
                             widget=forms.EmailInput(attrs={'autofocus': True, 'class': 'form-control'}), validators=[
            RegexValidator(regex=email_pattern, message="Please enter a valid email address.")])


class UserPasswordChange(PasswordChangeForm):
    old_password = forms.CharField(label=_('Old Password'), strip=False, required=True, widget=forms.PasswordInput(
        attrs={'autocomplete': 'current-password', 'class': 'form-control', 'autofocus': 'True'}))
    new_password1 = forms.CharField(label=_('New Password'), strip=False, required=True, widget=forms.PasswordInput(
        attrs={'autocomplete': 'new-password', 'class': 'form-control'}),
                                    help_text=password_validation.password_validators_help_text_html(), validators=[
            RegexValidator(regex=password_pattern,
                           message="Password must contain at least 8 characters, including at least one digit, one lowercase letter, one uppercase letter, and one special character.")])
    new_password2 = forms.CharField(label=_('Password'), strip=False, required=True, widget=forms.PasswordInput(
        attrs={'autocomplete': 'new-password', 'class': 'form-control'}))

    def clean_password2(self):
        new_password1 = self.cleaned_data.get("new_password1")
        new_password2 = self.cleaned_data.get("new_password2")
        if new_password1 and new_password2 and new_password1 != new_password2:
            raise ValidationError("Passwords do not match")
        return new_password2


class UserSetPasswordForm(SetPasswordForm):
    error_messages = {
        "password_mismatch": _("The confirm password doesn't match with new password."),
    }
    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'class': 'form-control'}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label=_("Confirm password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'class': 'form-control'}),
    )


class GroupPermissionForm(forms.ModelForm):
    permissions = forms.ModelMultipleChoiceField(
        queryset=Permission.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={"class": "form-control"}),
        required=False,
        label="Permissions",
        help_text="Select the permissions for the group.",
    )

    class Meta:
        model = Group
        fields = ['name', 'permissions']

    def __init__(self, *args, **kwargs):
        group = kwargs.pop('group', None)
        super().__init__(*args, **kwargs)
        if group and isinstance(group, Group):  # Ensure 'group' is a Group instance
            self.fields['permissions'].initial = group.permissions.all()


class CustomLoginForm(forms.Form):
    username = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'})
    )

class TeacherForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TeacherForm, self).__init__(*args, **kwargs)
        for field in ['profile_photo', 'first_name', 'last_name', 'phone_number', 'email', 'aadhar_number', 'father_name', 'mother_name', 'gender', 'religion', 'per_city_or_village', 'per_pincode', 'per_district', 'cor_city_or_village', 'cor_pincode', 'cor_district', 'nationality', 'joining_date', 'pan_card','bank_name', 'bank_account_no', 'ifsc_code']:
            self.fields[field].required = True

        self.fields['cor_district'].choices = DISTRICT_CHOICES
        self.fields['per_district'].choices = DISTRICT_CHOICES
        self.fields['subject'].empty_label = "Select Subject"
        today = datetime.date.today()
        self.fields['joining_date'].widget.attrs.update({'max': today})
        self.fields['subject'].queryset = Subject.objects.filter(is_active=True)

    class Meta:
        model = Teacher
        fields = "__all__"
        widgets = {
            'profile_photo': forms.FileInput(attrs={'placeholder': 'Profile Photo', 'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'placeholder': 'First name', 'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Last name', 'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'placeholder': 'Phone number', 'class': 'form-control'}),
            'email': forms.TextInput(attrs={'placeholder': 'Email Address', 'class': 'form-control'}),
            'aadhar_number': forms.TextInput(attrs={'placeholder': 'Aadhar Card', 'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'select2'}),
            'religion': forms.Select(attrs={'class': 'select2'}),
            'father_name': forms.TextInput(attrs={'placeholder': 'Father Name', 'class': 'form-control'}),
            'mother_name': forms.TextInput(attrs={'placeholder': 'Mother Name', 'class': 'form-control'}),
            'per_house_no': forms.TextInput(attrs={'placeholder': 'House Number', 'class': 'form-control'}),
            'per_landmark': forms.TextInput(attrs={'placeholder': 'Landmark', 'class': 'form-control'}),
            'per_city_or_village': forms.TextInput(attrs={'placeholder': 'City/Village', 'class': 'form-control'}),
            'per_pincode': forms.TextInput(attrs={'placeholder': 'Pincode', 'class': 'form-control'}),
            'per_district': forms.Select(attrs={'placeholder': 'Select District', 'class': 'select2'}),
            'cor_house_no': forms.TextInput(attrs={'placeholder': 'House Number', 'class': 'form-control'}),
            'cor_landmark': forms.TextInput(attrs={'placeholder': 'Landmark', 'class': 'form-control'}),
            'cor_city_or_village': forms.TextInput(attrs={'placeholder': 'City/Village', 'class': 'form-control'}),
            'cor_pincode': forms.TextInput(attrs={'placeholder': 'Pincode', 'class': 'form-control'}),
            'cor_district': forms.Select(attrs={'placeholder': 'Select District', 'class': 'select2'}),
            'subject': forms.Select(attrs={'class': 'select2'}),
            'nationality': forms.TextInput(attrs={'placeholder': 'Nationality', 'class': 'form-control'}),
            'joining_date': forms.DateInput(attrs={'type': 'date', 'placeholder': 'Select Joining Date', 'class': 'form-control'}),
            'pan_card': forms.TextInput(attrs={'placeholder': 'Pan Card', 'class': 'form-control'}),
            'bank_name': forms.TextInput(attrs={'placeholder': 'Bank Name', 'class': 'form-control'}),
            'bank_account_no': forms.TextInput(attrs={'placeholder': 'Account No.', 'class': 'form-control'}),
            'ifsc_code': forms.TextInput(attrs={'placeholder': 'IFSC Code', 'class': 'form-control'}),
            'is_active': forms.CheckboxInput(attrs={'placeholder': 'Active Status', 'class': 'form-control'}),
        }

        def clean_email(self):
            email = self.cleaned_data.get('email')
            if Teacher.objects.filter(email=email).exists():
                raise ValidationError("A teacher with this email already exists.")
            return email

        def clean_phone_number(self):
            phone_number = self.cleaned_data.get('phone_number')
            if Teacher.objects.filter(phone_number=phone_number).exists():
                raise ValidationError("A teacher with this phone number already exists.")
            return phone_number


class SubjectForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(SubjectForm, self).__init__(*args, **kwargs)
        self.fields['subject_name'].required = True
        self.fields['subject_code'].required = True
        self.fields['subject_name'].validators = [RegexValidator(regex=name_pattern, message="Subject name can only contain letters and spaces.")]
        self.fields['subject_code'].validators = [RegexValidator(regex='^\d{3}$', message="Please enter a valid 3-digit subject_code.")]

    class Meta:
        model = Subject
        fields = "__all__"
        widgets = {
            'subject_name': forms.TextInput(attrs={'placeholder': 'Subject name', 'class': 'form-control'}),
            'subject_code': forms.TextInput(attrs={'placeholder': 'Subject code', 'class': 'form-control'}),
            'is_active': forms.CheckboxInput(attrs={'placeholder': 'Active Status', 'class': 'form-control'}),
        }


class StudentClassForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(StudentClassForm, self).__init__(*args, **kwargs)
        self.fields['class_name'].required = True
        self.fields['assigning_teacher'].required = False

        self.fields['assigning_teacher'].empty_label = "Select Teacher"

School/management/templates/fee-structure-edit.html
{% extends 'base.html' %}
{% load static %}
{%block content%}
    <!-- Page Area Start Here -->
    <div class="dashboard-page-one">
        {% include 'sidebar.html' %}
        <div class="dashboard-content-one">
            <!-- Breadcubs Area Start Here -->
            <div class="breadcrumbs-area">
                <h3>Admin Dashboard</h3>
                <ul>
                    <li>
                        <a href="{% url 'homepage' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'fee structure add' %}">Fee</a>
                    </li>
                    <li>Edit Fee Structure</li>
                </ul>
            </div>
            <!-- Breadcubs Area End Here -->
            <!-- Group table area start here-->
            <div class="card height-auto">
                <div class="card-body">
                    <div class="heading-layout1">
                        <div class="item-title">
                            <h3>Edit Fee Structure</h3>
                        </div>
                    </div>
                    {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">{{ error }}</div>
                        {% endfor %}
                    {%endif%}
                    <form action='' method="post" class="new-added-form" id="editForm" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="{{form.class_id.id_for_label }}">{{form.class_id.label}}</label>
                                    {{ form.class_id }}
                                    {% for error in form.class_id.errors%}
                                    <small class="text-danger">{{error}}</small>
                                    {%endfor%}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="{{form.monthly_fee.id_for_label }}">{{form.monthly_fee.label}}</label>
                                    {{ form.monthly_fee }}
                                    {% for error in form.monthly_fee.errors%}
                                    <small class="text-danger">{{error}}</small>
                                    {%endfor%}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="{{form.admission_fee.id_for_label }}">{{form.admission_fee.label}}</label>
                                    {{ form.admission_fee }}
                                    {% for error in form.admission_fee.errors%}
                                    <small class="text-danger">{{error}}</small>
                                    {%endfor%}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="{{form.first_quarter_exam_fee.id_for_label }}">{{form.first_quarter_exam_fee.label}}</label>
                                    {{ form.first_quarter_exam_fee }}
                                    {% for error in form.first_quarter_exam_fee.errors%}
                                    <small class="text-danger">{{error}}</small>
                                    {%endfor%}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="{{form.half_year_exam_fee.id_for_label }}">{{form.half_year_exam_fee.label}}</label>
                                    {{ form.half_year_exam_fee }}
                                    {% for error in form.half_year_exam_fee.errors%}
                                    <small class="text-danger">{{error}}</small>
                                    {%endfor%}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="{{form.second_quarter_exam_fee.id_for_label }}">{{form.second_quarter_exam_fee.label}}</label>
                                    {{ form.second_quarter_exam_fee }}
                                    {% for error in form.second_quarter_exam_fee.errors%}
                                    <small class="text-danger">{{error}}</small>
                                    {%endfor%}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="{{form.annual_exam_fee.id_for_label }}">{{form.annual_exam_fee.label}}</label>
                                    {{ form.annual_exam_fee }}
                                    {% for error in form.annual_exam_fee.errors%}
                                    <small class="text-danger">{{error}}</small>
                                    {%endfor%}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="{{form.board_reg_fee.id_for_label }}">{{form.board_reg_fee.label}}</label>
                                    {{ form.board_reg_fee }}
                                    {% for error in form.board_reg_fee.errors%}
                                    <small class="text-danger">{{error}}</small>
                                    {%endfor%}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="{{form.board_fee.id_for_label }}">{{form.board_fee.label}}</label>
                                    {{ form.board_fee }}
                                    {% for error in form.board_fee.errors%}
                                    <small class="text-danger">{{error}}</small>
                                    {%endfor%}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="{{form.admit_card_fee.id_for_label }}">{{form.admit_card_fee.label}}</label>
                                    {{ form.admit_card_fee }}
                                    {% for error in form.admit_card_fee.errors%}
                                    <small class="text-danger">{{error}}</small>
                                    {%endfor%}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="{{form.practical_1_fee.id_for_label }}">{{form.practical_1_fee.label}}</label>
                                    {{ form.practical_1_fee }}
                                    {% for error in form.practical_1_fee.errors%}
                                    <small class="text-danger">{{error}}</small>
                                    {%endfor%}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="{{form.practical_2_fee.id_for_label }}">{{form.practical_2_fee.label}}</label>
                                    {{ form.practical_2_fee }}
                                    {% for error in form.practical_2_fee.errors%}
                                    <small class="text-danger">{{error}}</small>
                                    {%endfor%}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="{{form.practical_3_fee.id_for_label }}">{{form.practical_3_fee.label}}</label>
                                    {{ form.practical_3_fee }}
                                    {% for error in form.practical_3_fee.errors%}
                                    <small class="text-danger">{{error}}</small>
                                    {%endfor%}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="{{form.practical_4_fee.id_for_label }}">{{form.practical_4_fee.label}}</label>
                                    {{ form.practical_4_fee }}
                                    {% for error in form.practical_4_fee.errors%}
                                    <small class="text-danger">{{error}}</small>
                                    {%endfor%}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-check">
                                    {{ form.is_active }}
                                    <label for="{{ form.is_active.id_for_label }}" class="form-check-label pl-5">
                                        {{ form.is_active.label }}
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group mg-t-8 text-right">
                            <button type="submit" class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark mr-3">Update Fee structure</button>
                            <button type="reset" class="btn-fill-lg bg-blue-dark btn-hover-yellow">Reset</button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- Group table area end here-->
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags %}
                    <div class="alert alert-success {{ message.tags }}" role="alert">{{ message }}</div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    </div>
{%endblock%}
{%block js%}
<script>
    $(document).ready(function() {
        // Initially hide all relevant fields
        $('#id_board_reg_fee').closest('.col-md-6').hide();
        $('#id_board_fee').closest('.col-md-6').hide();
        $('#id_practical_1_fee').closest('.col-md-6').hide();
        $('#id_practical_2_fee').closest('.col-md-6').hide();
        $('#id_practical_3_fee').closest('.col-md-6').hide();
        $('#id_practical_4_fee').closest('.col-md-6').hide();

        // Function to show/hide fields based on class selection
        $('#id_class_id').change(function() {
            var selectedClass = $(this).val();

            // Show board_reg_fee for 9th or 11th class
            if (selectedClass === '9th_class' || selectedClass === '11th_class') {
                $('#id_board_reg_fee').closest('.col-md-6').show();
            } else {
                $('#id_board_reg_fee').closest('.col-md-6').hide();
            }

            // Show board_fee and practical fees for 10th or 12th class
            if (selectedClass === '10th_class' || selectedClass === '12th_class') {
                $('#id_board_fee').closest('.col-md-6').show();
                $('#id_practical_1_fee').closest('.col-md-6').show();
                $('#id_practical_2_fee').closest('.col-md-6').show();
                $('#id_practical_3_fee').closest('.col-md-6').show();
                $('#id_practical_4_fee').closest('.col-md-6').show();
            } else {
                $('#id_board_fee').closest('.col-md-6').hide();
                $('#id_practical_1_fee').closest('.col-md-6').hide();
                $('#id_practical_2_fee').closest('.col-md-6').hide();
                $('#id_practical_3_fee').closest('.col-md-6').hide();
                $('#id_practical_4_fee').closest('.col-md-6').hide();
            }
        });
    });
</script>
{%endblock%}

School/management/templates/footer.html
{% load static %}
<!-- jquery-->
<script src="{% static 'js/jquery-3.3.1.min.js'%}"></script>
<!-- Plugins js -->
<script src="{% static 'js/plugins.js'%}"></script>
<!-- Popper js -->
<script src="{% static 'js/popper.min.js'%}"></script>
<!-- Bootstrap js -->
<script src="{% static 'js/bootstrap.min.js'%}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.full.min.js"></script>
<!-- Scroll Up Js -->
<script src="{% static 'js/jquery.scrollUp.min.js'%}"></script>
<script src="{% static 'js/select2.min.js'%}"></script>
<!-- Scroll Up Js -->
<script src="{% static 'js/jquery.dataTables.min.js'%}"></script>
<!-- Custom Js -->
<script src="{% static 'js/main.js'%}"></script>

School/management/templates/group-edit.html
{% extends 'base.html' %}
{% load static %}
{%block content%}
    <!-- Page Area Start Here -->
    <div class="dashboard-page-one">
        {% include 'sidebar.html' %}
        <div class="dashboard-content-one">
            <!-- Breadcubs Area Start Here -->
            <div class="breadcrumbs-area">
                <h3>Admin Dashboard</h3>
                <ul>
                    <li>
                        <a href="{% url 'homepage' %}">Home</a>
                    </li>
                    <li>Groups</li>
                </ul>
            </div>
            <!-- Breadcubs Area End Here -->
            <!-- Group table area start here-->
            <div class="card height-auto">
                <div class="card-body">
                    <div class="heading-layout1">
                        <div class="item-title">
                            <h3>Update Permissions for {{group.name}}</h3>
                        </div>
                    </div>
                    <form action="" method="post" class="new-added-form">
                        {% csrf_token %}

                        <!-- Group Name Field -->
                        <div class="form-group">
                            <label for="{{ form.name.id_for_label }}">Name:</label>
                            <input type="{{ form.name.field.widget.input_type }}"
                                   name="{{ form.name.html_name }}"
                                   value="{{ form.name.value|default_if_none:'' }}"
                                   maxlength="150"
                                   required
                                   id="{{ form.name.id_for_label }}"
                                   class="form-control">
                        </div>

                        <!-- Permissions Checkboxes -->
                        <label class="mt-3">Permissions:</label>
                        <div id="id_permissions" class="row">
                            {% for checkbox in form.permissions %}
                                <div class="col-xl-3 col-lg-6 col-12">
                                    <div class="form-check">
                                        <!-- Render each checkbox -->
                                        {{ checkbox.tag }}
                                        <label for="{{ checkbox.id_for_label }}" class="form-check-label">
                                            {{ checkbox.choice_label }}
                                        </label>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <!-- Form Submit Buttons -->
                        <div class="col-12 form-group mg-t-8">
                            <button type="submit" class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark">Save</button>
                            <button type="reset" class="btn-fill-lg bg-blue-dark btn-hover-yellow">Reset</button>
                        </div>
                    </form>
                    <div class="mt-4">
                        {% if messages %}
                            {% for message in messages %}
                                {% if message.tags %}
                                <div class="alert alert-success {{ message.tags }}" role="alert">{{ message }}</div>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
            <!-- Group table area end here-->
        </div>
    </div>
{%endblock%}